# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# Stripe Terminal API Key (test mode)
STRIPE_TERMINAL_API_KEY=sk_test_51G0K5CB1h7Ho0bBU5bLWYJ57kaHO2aMOdTZMysBOqDh3bWh9PbBDaowkNS7S7ac28sg6SXw4bMjVIVVSyzXaWGrU005iKXElNK

# Backend URL
BACKEND_URL=https://api-001.sajet.us
